### ISSUE TITLE
not working in st3 windows

### ISSUE THREAD

**Issue by TracerLee** [polygonplanet/ESLint#1]
module.js:327
    throw err;
    ^

Error: Cannot find module 'eslint'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)

How to solve this problem? something setting wrong? The node module was already installed by npm.

**Comment by polygonplanet** [comment]
Maybe, npm's `eslint` module is not installed.
Install `eslint` globally by typing the following in a terminal:

```
npm install -g eslint
```

**Comment by TracerLee** [comment]
Thx
