### ISSUE TITLE
Setting node_modules_path to use active project's dependencies

### ISSUE THREAD

**Issue by joeyfigaro** [polygonplanet/ESLint#11]
Is there any way to set `node_modules_path` to use whatever `node_modules` directory exists in an active project?

**Comment by polygonplanet** [comment]
Currently, this module supports only to use global eslint.
Do you want to use other eslint' version in each project?

**Comment by abdurrahmanekr** [comment]
@polygonplanet absolute 👍

**Comment by kylemh** [comment]
+1 for this feature. I'd like to use this Package over SublimeLinter-contrib-eslint because it's a healthier repo, but I need to have the ability to shift rules depending on a project's `.eslintrc` to make the switch a reality.

**Comment by polygonplanet** [comment]
v5.0.0 Fix to use current working directory's node_modules/eslint in an active project

**Comment by videni** [comment]
@polygonplanet， it seems the v5.0.0 doesn't work as expected. are you sure it will use current active project settings?
