### ISSUE TITLE
ESLint couldn't find a configuration file.

### ISSUE THREAD

**Issue by zengxiaoluan** [polygonplanet/ESLint#16]
我已经配置了eslint的配置文件：
`{`
`"node_path": "C:/Program Files/nodejs",`
`  "node_modules_path": "C:/Users/10653/AppData/Roaming/npm/node_modules/eslint/bin",`
 ` "config_file": "D:/dev/tw591/public/.eslintrc.json"`
`}`

当我执行ctrl + alt + e时，报错了：

> ESLint: 4.6.1.
> ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:
> 
>     eslint --init
> 
> ESLint looked for configuration files in C:\Users\10653\AppData\Roaming\npm\node_modules\eslint\bin and its ancestors.

这是为什么呢？

**Comment by zengxiaoluan** [comment]
I have solved this problem that is caused by using a .json config file not a .js config file, thanks for your creation.

**Comment by polygonplanet** [comment]
OK, thanks for report!
