### ISSUE TITLE
Linting PHP files does not work

### ISSUE THREAD

**Issue by ipkpjersi** [polygonplanet/ESLint#18]
I was instructed to post this here by sublimelinter: https://github.com/SublimeLinter/SublimeLinter3/issues/692

#### `SublimeLinter` console output

![](https://i.imgur.com/7bNpBOR.png)
https://hastebin.com/givewiceyo.cs

#### `eslint` output from command line

https://hastebin.com/osotekeran.coffeescript

#### Additional info if needed (ST version, OS, configuration)

Here is my ESLintrc.js file: 

https://hastebin.com/ezasepohex.java

Sublime 3143, Ubuntu 16.04 LTS with Xfce. Using eslint v4.13.0, node v6.12.2, npm v3.10.10.

I have tried sublime linter eslint by roadhump and also by polygonplanet, neither have working linting for PHP files. The traceback only happens in the polygonplanet version of sublime eslint and not the roadhump version.

Do note that running ESLint manually with the command palette, I can see warnings even though they do not show up in the gutter like they are supposed to: ![](https://i.imgur.com/qifnwLY.png)

**Comment by polygonplanet** [comment]
Sublime Text Eslint assumes behavior with javascript file (ie, extension 'js').
We don't support linting on PHP file.
However, this plugin running by eslint. it may work if it works well with eslint settings.
