### ISSUE TITLE
Typescript 3.7 is not supported

### ISSUE THREAD

**Issue by alyzhao** [polygonplanet/ESLint#25]
WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.6.0

YOUR TYPESCRIPT VERSION: 3.7.2

Please only submit bug reports when using the officially supported version.

**Comment by polygonplanet** [comment]
This plugin does not use TypeScript or typescript-estree, it is for eslint. the issue for another repository...?
