### ISSUE TITLE
Default OSX Key Binding Shouldn't Be Ctrl+e

### ISSUE THREAD

**Issue by aqualad** [polygonplanet/ESLint#7]
Globally binding to `ctrl + e` on OSX is very intrusive to common OSX workflow.  `ctrl + a` and `ctrl + e` are standard "jump to beginning/end of line" hotkeys systemwide.

Please consider using a different default shortcut.

**Comment by polygonplanet** [comment]
OK, Change to `ctrl + alt + e` (`Cmd + Option + e`)
